
--https://www.hackerrank.com/challenges/the-report/problem

CREATE TABLE STUDENTS
(
ID INT,
NAME VARCHAR(50),
MARKS INT
);

CREATE TABLE GRADES
(
GRADE INT,
MIN_MARK INT,
MAX_MARK INT
);

INSERT INTO STUDENTS VALUES 
(19,'Samantha',87),(21,'Julia',96),(11 ,'Britney', 95),(32 ,'Kristeen', 100),(12 ,'Dyana' ,55),
(13 ,'Jenny' ,66),(14 ,'Christene', 88),(15 ,'Meera' ,24),(16 ,'Priya' ,76),(17 ,'Priyanka' ,77),
(18 ,'Paige' ,74),(19 ,'Jane' ,64),(21 ,'Belvet', 78),(31 ,'Scarlet', 80),(41 ,'Salma' ,81),
(51 ,'Amanda' ,34),(61 ,'Heraldo', 94),(71 ,'Stuart' ,99),(81 ,'Aamina' ,77),(76 ,'Amina' ,89),(91 ,'Vivek' ,84);


INSERT INTO GRADES VALUES
(1, 0 ,9),(2, 10,19),(3, 20 ,29),(4 ,30 ,39),(5 ,40 ,49),
(6 ,50 ,59),(7 ,60 ,69),(8 ,70 ,79),(9 ,80 ,89),(10 ,90, 100);

SELECT * FROM STUDENTS
ORDER BY MARKS;
SELECT * FROM GRADES;

SELECT
*
FROM 
STUDENTS S JOIN GRADES G ON
S.MARKS BETWEEN G.MIN_MARK AND G.MAX_MARK;



SELECT
S.NAME,G.GRADE,S.MARKS
FROM 
STUDENTS S JOIN GRADES G ON
S.MARKS BETWEEN G.MIN_MARK AND G.MAX_MARK WHERE G.GRADE>=8
ORDER BY S.MARKS DESC,S.NAME

SELECT
NULL AS NAME,G.GRADE,S.MARKS
FROM 
STUDENTS S JOIN GRADES G ON
S.MARKS BETWEEN G.MIN_MARK AND G.MAX_MARK WHERE G.GRADE<8
ORDER BY G.GRADE DESC,S.MARKS; 



SELECT
G.GRADE,S.MARKS,
COUNT(*)OVER (PARTITION BY G.GRADE ORDER BY S.MARKS DESC) AS RN
FROM 
STUDENTS S JOIN GRADES G ON
S.MARKS BETWEEN G.MIN_MARK AND G.MAX_MARK;


SELECT 
A.NAMES,A.GRADE,A.MARKS 
FROM 
	(SELECT
	CASE WHEN G.GRADE>=8 THEN S.NAME
	END AS NAMES,G.GRADE,S.MARKS
	FROM 
	STUDENTS S JOIN GRADES G ON
	S.MARKS BETWEEN G.MIN_MARK AND G.MAX_MARK
	) 
AS A 
LEFT JOIN STUDENTS AS S ON
S.NAME=A.NAMES
ORDER BY S.MARKS DESC,A.MARKS; 


--Submissions
SELECT
    CASE WHEN G.GRADE>=8 THEN S.NAME
    END AS NAMES,G.GRADE,S.MARKS
FROM 
STUDENTS S JOIN GRADES G ON
S.MARKS BETWEEN G.MIN_MARK AND G.MAX_MARK
ORDER BY G.GRADE DESC,S.NAME

